#!/bin/bash
salt=$(sha256sum $0)
echo "key:"
read input
echo "new key:"
echo $input$salt | sha256sum | base64 | head -c 32
echo ""

#echo "#$(echo "$RANDOM $RANDOM" | shasum | base64)" >> salti.sh 

#MGIwMGYxNTQzODNkYjVhN2VlMDMzYWY4MDYyMWVhYmZkMDFkYmNlYiAgLQo=
#Y2ZhZmIzMWIzOGFlZjgzYmU0NWJhYzE2YTk0YWUwNTgzZjNmZDI0NyAgLQo=
#MjcwZDRiMmVkZThkYjE3NmJkNzJiYmQwZDU0MzlkMWI4Yzg0OTM4YiAgLQo=
#NjU5NDMyODEwZmYxODliMDk5MDI2ZGU2OWY4MDRhYTZmZDk3MTlhYSAgLQo=
#MDU1NDc0NjM3NWUxYjVjNWZmYTEwYjA1ZTRlODliYWRhYzllNzI0ZiAgLQo=
#NzA0MjAwNDFlOTIyODQ0YTI3YjcxYTFiYWVmNjBhODY2ZDJkYzkwMSAgLQo=
#NTQxNTMwNGM2MmEzNDg1MzA1MGYzYTQ5ZDNiZjFmMTUzYmJiYzQ2MSAgLQo=
#NDhhYjczMmIwY2QzYTRkMTRjNTk4NmUwMTQ2N2Q2YzlmZjYyMGU2NiAgLQo=
#OTVmYmJkY2FiZDdkNzhjYjRhNDM0MDBhZTJmZDgxZmVjMDg1Mzg4OSAgLQo=
#NjZkZjU2ZTQyNGI4OWMwODZlZGYzZmI1YmFlMGYyNWIwMzMyN2YwMiAgLQo=
